# Generated by Django 6.0.4 on 2026-04-29 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'bank_accounts',
                'indexes': [models.Index(fields=['code'], name='bank_accoun_code_6a9cc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.DecimalField(decimal_places=4, max_digits=20)),
                ('statement_date', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('overdraft_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('reserved_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('entry_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(db_column='bank_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='core.bankaccount')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
                'db_table': 'bank_statements',
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('original_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(max_length=20)),
                ('entry_type', models.CharField(max_length=50)),
                ('bank_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('reconciliation_status', models.CharField(choices=[('pending', 'Pendiente'), ('reconciled', 'Conciliado'), ('discrepancy', 'Discrepancia')], default='pending', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(db_column='bank_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount')),
                ('bank_statement', models.ForeignKey(db_column='bank_statement_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankstatement')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'bank_statement_transactions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'offices',
                'indexes': [models.Index(fields=['code'], name='offices_code_856b73_idx')],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Operación',
                'verbose_name_plural': 'Tipos de Operaciones',
                'db_table': 'operations',
                'indexes': [models.Index(fields=['code'], name='operations_code_7a6bea_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionChangeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='core.bankstatementtransaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'db_table': 'transaction_change_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['model_name'], name='audit_logs_model_n_da6855_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['statement_date'], name='bank_statem_stateme_700ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account'], name='bank_statem_bank_ac_380d05_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['office_code'], name='bank_statem_office__79de09_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['currency'], name='bank_statem_currenc_598d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['reconciliation_status'], name='bank_statem_reconci_24755a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['created_at'], name='bank_statem_created_f30f80_idx'),
        ),
    ]
